# Big Clinical Data and Literature Search

<!---Submit to RPubs--> 
This Open Design is licensed under a Creative Commons Attribution - Non commercial 3.0 Unported License. see full license at the end of this file. 

# Abstract 

# Introduction 
* Despite all the hype about Big Clinical Data, literature search for biomedical research and commercialization still remain a manual craft. In other words, researchers and innovators sit in front of the computer and search a couple of bibliographic databases more familiar to them, adding whatever they might know by heart.
* lit search on free mechanisms to enhance search, tagging using Semantic Web and 
*objective 

# Methods 
*public data
*simulation 
*mturk  

# Results 
*tables 
*graphics 

# Discussion 
*blending sit cog map 
*lit review with bio2rdf and Mendeley using regexp for emails
*photos, videos, and 3D models 

# Creative Commons License 
This Open Design is licensed under a Creative Commons Attribution - Non commercial 3.0 Unported License. You are free: to Share — to copy, distribute and transmit the work to Remix — to adapt the work, under the following conditions: Attribution — You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work). Noncommercial — You may not use this work for commercial purposes. With the understanding that: Waiver — Any of the above conditions can be waived if you get permission from the copyright holder. Public Domain — Where the work or any of its elements is in the public domain under applicable law, that status is in no way affected by the license. Other Rights — In no way are any of the following rights affected by the license: Your fair dealing or fair use rights, or other applicable copyright exceptions and limitations; The author's moral rights; Rights other persons may have either in the work itself or in how the work is used, such as publicity or privacy rights. Notice — For any reuse or distribution, you must make clear to others the license terms of this work. The best way to do this is with a link to this web page. For more details see http://creativecommons.org/licenses/by-nc/3.0/

